server:
  port: 8099
  servlet:
    context-path: /advertisement-notification-system
kafka:
  bootstrap-servers: localhost:9092
  topic:
    groupId: notification
    notification: topic-advertisement-notifications
